apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp
	labels:
	   app: myapp	   
spec:
  template:
     metadata:
       name: mypod
	   labels:
	     app: myapp

     spec: 
       containers:
          - name: myapp
	        image: nginx:latest
  replicas: 2
  selector:
     matchLabels:
	    app: mypp
		